---
name: Mockingbird
version: 2.2.0
main: ethaniccc\Mockingbird\Mockingbird
api: 3.15.0
mcpe-protocol: 408

permissions:
  mockingbird:
    children:
      mockingbird.alerts:
        description: Get Mockingbird anti-cheat alerts.
        default: op
      mockingbird.debug:
        description: Get Mockingbird debug messages in-game
        default: op
...
